<<<<<<< HEAD
INSERT INTO travel (user_email, place, description)
VALUES
('user1@example.com', 'Paris, France', 'Explored the iconic Eiffel Tower and indulged in delicious French pastries.'),
('user2@example.com', 'Kyoto, Japan', 'Visited serene temples, enjoyed cherry blossoms, and experienced traditional tea ceremonies.'),
('user3@example.com', 'New York City, USA', 'Explored Times Square, walked through Central Park, and saw a Broadway show.'),
('user4@example.com', 'Rome, Italy', 'Visited the Colosseum, threw a coin in the Trevi Fountain, and savored authentic Italian pasta.'),
('user5@example.com', 'Cape Town, South Africa', 'Enjoyed breathtaking views from Table Mountain and went on a safari in Kruger National Park.'),
('user6@example.com', 'Barcelona, Spain', 'Strolled down La Rambla, admired Gaudi\'s architecture, and savored paella by the beach.'),
('user7@example.com', 'Tokyo, Japan', 'Explored the bustling districts of Shibuya and Shinjuku, and tasted delicious ramen.'),
('user8@example.com', 'London, UK', 'Visited the British Museum, walked along the River Thames, and experienced London\'s rich history.'),
('user9@example.com', 'Rio de Janeiro, Brazil', 'Relaxed on Copacabana Beach, hiked up Sugarloaf Mountain, and celebrated Carnival.'),
('user10@example.com', 'Dubai, UAE', 'Spectacular views from the Burj Khalifa, shopping at the Dubai Mall, and desert safari adventures.'),
('user11@example.com', 'Marrakech, Morocco', 'Explored the vibrant souks, visited the Jardin Majorelle, and enjoyed traditional Moroccan cuisine.'),
('user12@example.com', 'Sydney, Australia', 'Explored the Sydney Opera House, Bondi Beach, and the historic Rocks district.'),
('user13@example.com', 'Istanbul, Turkey', 'Visited the Hagia Sophia, explored the Grand Bazaar, and cruised the Bosphorus.'),
('user14@example.com', 'Prague, Czech Republic', 'Walked through Old Town Square, admired Prague Castle, and enjoyed Czech beer.'),
('user15@example.com', 'Seoul, South Korea', 'Explored vibrant street markets, visited Gyeongbokgung Palace, and tried Korean BBQ.'),
('user16@example.com', 'Vienna, Austria', 'Attended a classical concert, explored Schönbrunn Palace, and enjoyed Viennese coffee.'),
('user17@example.com', 'Cairo, Egypt', 'Explored the Pyramids of Giza, visited the Sphinx, and cruised the Nile River.'),
('user18@example.com', 'Amsterdam, Netherlands', 'Cycled along picturesque canals, visited Anne Frank House, and explored the Van Gogh Museum.'),
('user19@example.com', 'Buenos Aires, Argentina', 'Danced the tango, explored Recoleta Cemetery, and enjoyed Argentine steak.'),
('user20@example.com', 'Bangkok, Thailand', 'Visited Wat Pho, explored the Grand Palace, and experienced the vibrant street life.'),
('user21@example.com', 'Athens, Greece', 'Explored the Acropolis, visited the Parthenon, and enjoyed Greek cuisine.'),
('user22@example.com', 'Hanoi, Vietnam', 'Explored the Old Quarter, visited Ho Chi Minh Mausoleum, and tried pho.'),
('user23@example.com', 'Edinburgh, Scotland', 'Visited Edinburgh Castle, hiked Arthur\'s Seat, and experienced the Royal Edinburgh Military Tattoo.'),
('user24@example.com', 'Cusco, Peru', 'Explored Machu Picchu, hiked the Inca Trail, and enjoyed Peruvian cuisine.'),
('user26@example.com', 'Reykjavik, Iceland', 'Visited the Blue Lagoon, explored the Golden Circle, and witnessed the Northern Lights.'),
('user27@example.com', 'Dubrovnik, Croatia', 'Walked the city walls, explored Old Town, and enjoyed the stunning Adriatic Sea views.'),
('user28@example.com', 'Krakow, Poland', 'Visited Wawel Castle, explored the historic Old Town, and experienced Polish cuisine.'),
('user29@example.com', 'Mumbai, India', 'Explored Bollywood studios, visited Gateway of India, and tasted authentic Indian street food.'),
('user30@example.com', 'Montreal, Canada', 'Explored Old Montreal, visited Mount Royal, and experienced the vibrant cultural scene.'),
('user31@example.com', 'Budapest, Hungary', 'Relaxed in thermal baths, visited Buda Castle, and enjoyed Hungarian goulash.'),
('user32@example.com', 'Santorini, Greece', 'Admired the white-washed buildings, watched the sunset in Oia, and explored ancient ruins.'),
('user33@example.com', 'Jerusalem, Israel', 'Visited the Western Wall, explored the Old City, and experienced the diverse cultural heritage.'),
('user34@example.com', 'Cartagena, Colombia', 'Wandered through colorful streets, visited Castillo San Felipe, and enjoyed Colombian cuisine.'),
('user35@example.com', 'Dublin, Ireland', 'Explored Trinity College, visited the Guinness Storehouse, and enjoyed traditional Irish music.'),
('user36@example.com', 'Oslo, Norway', 'Visited the Viking Ship Museum, explored Holmenkollen, and enjoyed the scenic fjords.'),
('user37@example.com', 'Casablanca, Morocco', 'Explored the Hassan II Mosque, walked along the Corniche, and enjoyed Moroccan tea.'),
('user38@example.com', 'Auckland, New Zealand', 'Visited the Sky Tower, explored Waiheke Island, and enjoyed Kiwi hospitality.'),
('user39@example.com', 'Granada, Spain', 'Explored the Alhambra, wandered through the Albayzín, and enjoyed tapas.'),
('user40@example.com', 'Cologne, Germany', 'Visited Cologne Cathedral, strolled along the Rhine River, and explored the historic Old Town.'),
('user41@example.com', 'Kuala Lumpur, Malaysia', 'Visited the Petronas Towers, explored Batu Caves, and experienced diverse Malaysian cuisine.'),
('user42@example.com', 'Nairobi, Kenya', 'Visited Nairobi National Park, explored Giraffe Centre, and enjoyed Maasai Mara Safari.'),
('user43@example.com', 'Bucharest, Romania', 'Explored the Palace of the Parliament, visited Herastrau Park, and enjoyed Romanian cuisine.'),
('user44@example.com', 'Brussels, Belgium', 'Visited Grand Place, enjoyed Belgian chocolates, and explored the Atomium.'),
('user45@example.com', 'Brisbane, Australia', 'Explored South Bank, visited Lone Pine Koala Sanctuary, and enjoyed the vibrant arts scene.'),
('user46@example.com', 'Seville, Spain', 'Visited the Alcazar, enjoyed Flamenco dancing, and explored the historic Jewish Quarter.'),
('user47@example.com', 'Anchorage, USA', 'Explored Chugach State Park, visited the Alaska Native Heritage Center, and enjoyed dog sledding.'),
('user48@example.com', 'Zurich, Switzerland', 'Explored Old Town, enjoyed Lake Zurich, and experienced Swiss chocolate and cheese.'),
('user49@example.com', 'Valletta, Malta', 'Visited St. John\'s Co-Cathedral, explored Upper Barrakka Gardens, and enjoyed Maltese cuisine.');
=======
INSERT INTO travel (user_email, place, description, travel_date, latitude, longitude)
VALUES
('user1@example.com', 'Paris, France', 'Explored the iconic Eiffel Tower and indulged in delicious French pastries.', '2023-03-15', 48.8566, 2.3522),
('user2@example.com', 'Kyoto, Japan', 'Visited serene temples, enjoyed cherry blossoms, and experienced traditional tea ceremonies.', '2022-09-25', 35.0116, 135.7681),
('user3@example.com', 'New York City, USA', 'Explored Times Square, walked through Central Park, and saw a Broadway show.', '2022-05-10', 40.7128, -74.0060),
('user4@example.com', 'Rome, Italy', 'Visited the Colosseum, threw a coin in the Trevi Fountain, and savored authentic Italian pasta.', '2022-07-20', 41.9028, 12.4964),
('user5@example.com', 'Cape Town, South Africa', 'Enjoyed breathtaking views from Table Mountain and went on a safari in Kruger National Park.', '2023-01-05', -33.918861, 18.423300),
('user6@example.com', 'Barcelona, Spain', 'Strolled down La Rambla, admired Gaudi\'s architecture, and savored paella by the beach.', '2022-11-08', 41.3851, 2.1734),
('user7@example.com', 'Tokyo, Japan', 'Explored the bustling districts of Shibuya and Shinjuku, and tasted delicious ramen.', '2022-12-15', 35.6895, 139.6917),
('user8@example.com', 'London, UK', 'Visited the British Museum, walked along the River Thames, and experienced London\'s rich history.', '2022-06-02', 51.5074, -0.1278),
('user9@example.com', 'Rio de Janeiro, Brazil', 'Relaxed on Copacabana Beach, hiked up Sugarloaf Mountain, and celebrated Carnival.', '2022-03-04', -22.9068, -43.1729),
('user10@example.com', 'Dubai, UAE', 'Spectacular views from the Burj Khalifa, shopping at the Dubai Mall, and desert safari adventures.', '2022-08-19', 25.276987, 55.296249),
('user11@example.com', 'Marrakech, Morocco', 'Explored the vibrant souks, visited the Jardin Majorelle, and enjoyed traditional Moroccan cuisine.', '2022-04-12', 31.6348, -7.9896),
('user12@example.com', 'Sydney, Australia', 'Explored the Sydney Opera House, Bondi Beach, and the historic Rocks district.', '2022-10-30', -33.8688, 151.2093),
('user13@example.com', 'Istanbul, Turkey', 'Visited the Hagia Sophia, explored the Grand Bazaar, and cruised the Bosphorus.', '2022-07-25', 41.0082, 28.9784),
('user14@example.com', 'Prague, Czech Republic', 'Walked through Old Town Square, admired Prague Castle, and enjoyed Czech beer.', '2022-09-08', 50.0755, 14.4378),
('user15@example.com', 'Seoul, South Korea', 'Explored vibrant street markets, visited Gyeongbokgung Palace, and tried Korean BBQ.', '2022-11-27', 37.5665, 126.9780),
('user16@example.com', 'Vienna, Austria', 'Attended a classical concert, explored Schönbrunn Palace, and enjoyed Viennese coffee.', '2022-12-03', 48.8566, 2.3522),
('user17@example.com', 'Cairo, Egypt', 'Explored the Pyramids of Giza, visited the Sphinx, and cruised the Nile River.', '2022-02-18', 30.0444, 31.2357),
('user18@example.com', 'Amsterdam, Netherlands', 'Cycled along picturesque canals, visited Anne Frank House, and explored the Van Gogh Museum.', '2022-05-22', 52.3676, 4.9041),
('user19@example.com', 'Buenos Aires, Argentina', 'Danced the tango, explored Recoleta Cemetery, and enjoyed Argentine steak.', '2023-02-09', -34.6118, -58.4173),
('user20@example.com', 'Bangkok, Thailand', 'Visited Wat Pho, explored the Grand Palace, and experienced the vibrant street life.', '2022-07-01', 13.7563, 100.5018),
('user21@example.com', 'Istanbul, Turkey', 'Explored the Hagia Sophia, explored the Grand Bazaar, and cruised the Bosphorus.', '2022-08-12', 41.0082, 28.9784),
('user22@example.com', 'Bangkok, Thailand', 'Visited Wat Pho, explored the Grand Palace, and experienced the vibrant street life.', '2022-06-29', 13.7563, 100.5018),
('user23@example.com', 'Sydney, Australia', 'Explored the Sydney Opera House, Bondi Beach, and the historic Rocks district.', '2023-02-10', -33.8688, 151.2093),
('user24@example.com', 'Vienna, Austria', 'Attended a classical concert, explored Schönbrunn Palace, and enjoyed Viennese coffee.', '2022-10-18', 48.8566, 2.3522);
>>>>>>> bc9a88451025005346002821dc7fcbce1dedd38a
